# Generated by Django 5.2.1 on 2025-05-15 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.IntegerField()),
                ('libelle', models.CharField(max_length=100)),
                ('piece_justificative', models.CharField(max_length=100)),
                ('debit', models.FloatField()),
                ('credit', models.FloatField()),
                ('asso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associations.associations')),
            ],
        ),
    ]
