# Generated by Django 5.1.2 on 2025-05-17 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0001_initial'),
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('categorie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comptabilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('libelle', models.CharField(max_length=100)),
                ('piece_justificative', models.CharField(max_length=100)),
                ('debit', models.FloatField()),
                ('credit', models.FloatField()),
                ('asso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associations.associations')),
                ('numero_compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptabilite.compte')),
            ],
        ),
        migrations.DeleteModel(
            name='GrandLivre',
        ),
    ]
