# Generated by Django 5.1.2 on 2025-05-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0003_comptabilite_editeur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comptabilite',
            old_name='asso',
            new_name='association',
        ),
    ]
