# Generated by Django 5.1.2 on 2025-05-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0004_rename_asso_comptabilite_association'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='id',
        ),
        migrations.AlterField(
            model_name='compte',
            name='numero',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
