# Generated by Django 5.2.1 on 2025-05-15 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Associations',
            fields=[
                ('asso', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president_associations', to=settings.AUTH_USER_MODEL)),
                ('treasurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasurer_associations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
